import { StyleSheet } from "react-native";
import { shimmerColor, white } from "../../Color/color";

export default StyleSheet.create({
  mainViewShimmer: {
    borderRadius: 8,
    elevation: 2,
    padding: 10,
    marginVertical: 10,
    marginHorizontal: 5,
    backgroundColor: white,
  },
  borderLineShimmer: { backgroundColor: shimmerColor, height: 0.5 },
  shimmerDirection: { marginTop: 20, flexDirection: "row" },
  shimmerProfile: { height: 25, width: 25, borderRadius: 20 },
  shimmerNameView: {
    height: 15,
    width: 150,
    marginTop: 5,
    marginLeft: 10,
    borderRadius: 5,
  },
  shimmerFlex: { flex: 1 },
  shimmerIconView: {
    marginTop: 10,
    height: 15,
    width: 75,
    borderRadius: 5,
  },
  shimmerBorderIconView: {
    marginTop: 10,
    height: 15,
    width: 150,
    borderRadius: 5,
  },
  shimmerLocationView: {
    borderRadius: 8,
    height: 50,
    elevation: 2,
    marginTop: 18,
  },
  bannerContainer: {
    height: 130,
    borderRadius: 10,
    margin: 5,
    padding: 10,
    flexDirection: "row",
  },
  shimmerItemView: {
    width: 110,
    height: 110,
    margin: 10,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  shimmerCardView: {
    borderRadius: 8,
    elevation: 2,
    padding: 10,
    marginTop: 20,
    backgroundColor: white,
  },
  commonMarginTop: { marginTop: 10 },
  shimmerUpperTextView: { height: 15, width: 75, borderRadius: 5 },
  shimmerLowerTextView: {
    height: 15,
    width: 150,
    marginTop: 10,
    borderRadius: 5,
  },
  lorryShimmerItemView: {
    marginTop: 10,
    flexDirection: "row",
  },
  lorryShimmerView: {
    borderRadius: 8,
    elevation: 2,
    padding: 10,
    margin: 1,
    marginTop: 20,
    backgroundColor: white,
  },
  dotView: { height: 10, width: 60, borderRadius: 5 },
  lorryTextShimmer: {
    height: 15,
    width: 200,
    marginLeft: 10,
    borderRadius: 8,
    flex: 1,
  },
  buttonView: {
    height: 40,
    width: 100,
    borderRadius: 5,
    justifyContent: "space-between",
  },
  buttonActiveView: {
    height: 50,
    width: 150,
    borderRadius: 8,
    justifyContent: "space-between",
    elevation: 2,
  },
  requestShimmer: {
    marginTop: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 8,
  },
});
