import {StyleSheet} from 'react-native';

import {
  privacyPolicy,
  textColor,
  GradientColor2,
  GradientColor3,
  pageBackground,
  inputColor,
  PrivacyPolicy,
  titleColor,
  white,
} from '../../Color/color';

export default StyleSheet.create({
  Container: {flex: 1, backgroundColor: '#FFFDFD'},
  DashboardHeaderView: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    elevation: 5,
    maxHeight: 60,
    padding: 10,
    backgroundColor: 'white',
    zIndex: 9999,
  },
  backIconView: {
    backgroundColor: '#fff',
    width: 38,
    height: 38,
    marginBottom: 24,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    borderRadius: 20,
    width: '100%',
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 38,
  },
  buttonTitile: {
    color: textColor,
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  backgroundView: {
    flex: 1,
    // padding: 10,
    // backgroundColor: pageBackground,
    // height: "100%",
    justifyContent: 'center',
  },
  backgroundViewContainer: {
    flex: 1,
    padding: 10,
    backgroundColor: pageBackground,
    height: '100%',
    justifyContent: 'center',
  },
  horizontalLine: {backgroundColor: '#AFAFAF', height: 1, marginVertical: 10},
  verticalLine: {
    backgroundColor: '#AFAFAF',
    width: 2,
    marginHorizontal: 15,
    height: '100%',
  },
  rowdirection: {flexDirection: 'row', alignItems: 'center'},
  smallImageHeaderTitle: {
    fontSize: 15,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  textStyle: {
    color: PrivacyPolicy,
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  dashboardHeaderVerifiedTitle: {
    fontSize: 12,
    color: GradientColor2,
    fontFamily: 'PlusJakartaSans-SemiBold',
    marginLeft: 5,
  },
  locationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  verifyTruck: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 20,
    borderColor: '#ccc',
    paddingVertical: 3,
    paddingHorizontal: 15,
    marginRight: 10,
    elevation: 2,
    backgroundColor: white,
  },
  point: {
    height: 8,
    width: 8,
    backgroundColor: PrivacyPolicy,
    borderRadius: 4,
    marginRight: 20,
    marginLeft: 10,
  },
  title: {
    fontWeight: '700',
    color: 'black',
    fontSize: 22,
    width: '80%',
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Medium',
  },
  rowDirection: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  bookingItem: (selected, id) => ({
    flex: 1,
    margin: 10,
    backgroundColor: selected === id ? GradientColor2 : '#000',
    padding: 10,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: GradientColor2,
  }),
  bookingTextItem: (selected, id) => ({
    color: selected === id ? '#fff' : '#000',
    fontFamily:
      selected === id ? 'PlusJakartaSans-SemiBold' : 'PlusJakartaSans-Regular',
    fontSize: 12,
  }),
  tabView: {
    flex: 1,
    marginTop: 60,
    paddingVertical: 10,
  },
  buttonTextStyle: {
    color: textColor,
    fontWeight: '700',
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  buttonstyle: {
    borderRadius: 8,
    justifyContent: 'center',
    padding: 14,
  },
  touchStyle: {
    marginBottom: 20,
    width: '50%',
    alignSelf: 'center',
  },
});
