// SignUp Actions or Login Actions
export const INIT_LOGIN = 'INIT_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Verify OTP Actions
export const INIT_VERIFY_OTP = 'INIT_VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

// Profile SetUp Actions
export const INIT_PROFILE_SETUP = 'INIT_PROFILE_SETUP';
export const PROFILE_SETUP_SUCCESS = 'PROFILE_SETUP_SUCCESS';
export const PROFILE_SETUP_FAILURE = 'PROFILE_SETUP_FAILURE';

// Add Lorry Actions
export const INIT_ADDLORRY = 'INIT_ADDLORRY';
export const ADDLORRY_SUCCESS = 'ADDLORRY_SUCCESS';
export const ADDLORRY_FAILURE = 'ADDLORRY_FAILURE';

// REQUEST_BOOKING Actions
export const INIT_REQUEST_BOOKING = 'INIT_REQUEST_BOOKING';
export const REQUEST_BOOKING_SUCCESS = 'REQUEST_BOOKING_SUCCESS';
export const REQUEST_BOOKING_FAILURE = 'REQUEST_BOOKING_FAILURE';

// ACCEPT_BOOKING Actions
export const INIT_ACCEPT_BOOKING = 'INIT_ACCEPT_BOOKING';
export const ACCEPT_BOOKING_SUCCESS = 'ACCEPT_BOOKING_SUCCESS';
export const ACCEPT_BOOKING_FAILURE = 'ACCEPT_BOOKING_FAILURE';

// Locations
export const INIT_LOCATION = 'INIT_LOCATION';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
export const LOCATION_FAILURE = 'LOCATION_FAILURE';

// Locations
export const INIT_DASHBOARD = 'INIT_DASHBOARD';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAILURE = 'DASHBOARD_FAILURE';

// Profile
export const INIT_PROFILE = 'INIT_PROFILE_DATA';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS_DATA';
export const PROFILE_FAILURE = 'PROFILE_FAILURE_DATA';

// Update Language
export const INIT_LANGUAGE = 'INIT_LANGUAGE';
export const LANGUAGE_SUCCESS = 'LANGUAGE_SUCCESS';
export const LANGUAGE_FAILURE = 'LANGUAGE_FAILURE';

// Post Loads
export const INIT_FIND_LOAD = 'INIT_FIND_LOAD';
export const FIND_LOAD_SUCCESS = 'FIND_LOAD_SUCCESS';
export const FIND_LOAD_FAILURE = 'FIND_LOAD_FAILURE';

// My Lorry
export const INIT_MYLORRY = 'INIT_MYLORRY';
export const MYLORRY_SUCCESS = 'MYLORRY_SUCCESS';
export const MYLORRY_FAILURE = 'MYLORRY_FAILURE';

// My Lorry Using Id
export const INIT_MYLORRY_BY_ID = 'INIT_MYLORRY_BY_ID';
export const MYLORRY_ID_SUCCESS = 'MYLORRY_ID_SUCCESS';
export const MYLORRY_ID_FAILURE = 'MYLORRY_ID_FAILURE';

// My Lorry Using Id
export const INIT_MYLOAD_BY_ID = 'INIT_MYLOAD_BY_ID';
export const MYLOAD_ID_SUCCESS = 'MYLOAD_ID_SUCCESS';
export const MYLOAD_ID_FAILURE = 'MYLOAD_ID_FAILURE';

// My Loads
export const INIT_MYLOAD = 'INIT_MYLOAD';
export const MYLOAD_SUCCESS = 'MYLOAD_SUCCESS';
export const MYLOAD_FAILURE = 'MYLOAD_FAILURE';

// Contact us
export const INIT_CONTACTUS = 'INIT_CONTACTUS';
export const CONTACTUS_SUCCESS = 'CONTACTUS_SUCCESS';
export const CONTACTUS_FAILURE = 'CONTACTUS_FAILURE';

// Contact us
export const INIT_GUIDE = 'INIT_GUIDE';
export const GUIDE_SUCCESS = 'GUIDE_SUCCESS';
export const GUIDE_FAILURE = 'GUIDE_FAILURE';

// Booking
export const INIT_BOOKING = 'INIT_BOOKING';
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS';
export const PENDING_BOOKING_SUCCESS = 'PENDING_BOOKING_SUCCESS';
export const ONGOING_BOOKING_SUCCESS = 'ONGOING_BOOKING_SUCCESS';
export const COMPLETE_BOOKING_SUCCESS = 'COMPLETE_BOOKING_SUCCESS';
export const BOOKING_FAILURE = 'BOOKING_FAILURE';

// Accept Reject
export const INIT_ACCEPT_REJECT = 'INIT_ACCEPT_REJECT';
export const ACCEPT_REJECT_SUCCESS = 'ACCEPT_REJECT_SUCCESS';
export const ACCEPT_REJECT_FAILURE = 'ACCEPT_REJECT_FAILURE';

// Notification
export const INIT_NOTIFICATION = 'INIT_NOTIFICATION';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';

// My Post Load
export const INIT_MYPOST_LOAD = 'INIT_MYPOST_LOAD';
export const MYPOST_LOAD_SUCCESS = 'MYPOST_LOAD_SUCCESS';
export const MYPOST_LOAD_FAILURE = 'MYPOST_LOAD_FAILURE';

// Wallet
export const INIT_WALLET = 'INIT_WALLET';
export const WALLET_SUCCESS = 'WALLET_SUCCESS';
export const WALLET_FAILURE = 'WALLET_FAILURE';

// Get Wallet
export const INIT_GET_WALLET = 'INIT_GET_WALLET';
export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS';
export const GET_WALLET_FAILURE = 'GET_WALLET_FAILURE';

// Logout
export const INIT_LOGOUT = 'INIT_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// Load Trucks
export const INIT_LOAD_TRUCK = 'INIT_LOAD_TRUCK';
export const LOAD_TRUCK_SUCCESS = 'LOAD_TRUCK_SUCCESS';
export const LOAD_TRUCK_FAILURE = 'LOAD_TRUCK_FAILURE';

// Rating
export const INIT_RATING = 'INIT_RATING';
export const RATING_SUCCESS = 'RATING_SUCCESS';
export const RATING_FAILURE = 'RATING_FAILURE';

// Get UserProfile
export const INIT_USER_PROFILE = 'INIT_USER_PROFILE';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';

// Status
export const INIT_STATUS_CHANGE = 'INIT_STATUS';
export const STATUS_CHANGE_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_CHANGE_FAILURE = 'STATUS_FAILURE';

// FindLorry
export const INIT_FIND_LORRY = 'INIT_FIND_LORRY';
export const FIND_LORRY_SUCCESS = 'FIND_LORRY_SUCCESS';
export const FIND_LORRY_FAILURE = 'FIND_LORRY_FAILURE';

// Modal location from
export const INIT_MODAL_LOCATION = 'INIT_MODAL_LOCATION';
export const MODAL_LOCATION_SUCCESS = 'MODAL_LOCATION_SUCCESS';
export const MODAL_LOCATION_CLEAR = 'MODAL_LOCATION_CLEAR';
export const MODAL_CLOSE_LOCATION = 'MODAL_CLOSE_LOCATION';

// Modal location from
export const INIT_SEARCH_FROM_ID = 'INIT_SEARCH_FROM_ID';
export const SEARCH_FROM_ID_SUCCESS = 'SEARCH_FROM_ID_SUCCESS';

// Modal location from
export const INIT_SEARCH_TO_ID = 'INIT_SEARCH_TO_ID';
export const SEARCH_TO_ID_SUCCESS = 'SEARCH_TO_ID_SUCCESS';

// Modal location To
export const INIT_MODAL_LOCATION_TO = 'INIT_MODAL_LOCATION_TO';
export const MODAL_LOCATION_TO_SUCCESS = 'MODAL_LOCATION_TO_SUCCESS';
export const MODAL_LOCATION_TO_CLEAR = 'MODAL_LOCATION_TO_CLEAR';

// Add Current Location
export const INIT_CURRENT_LOCATION = 'INIT_CURRENT_LOCATION';
export const CURRENT_LOCATION_SUCCESS = 'CURRENT_LOCATION_SUCCESS';
export const CURRENT_LOCATION_FAILURE = 'CURRENT_LOCATION_FAILURE';

// Lorry Require
export const INIT_LORRY_REQUIRE = 'INIT_LORRY_REQUIRE';
export const LORRY_REQUIRE_SUCCESS = 'LORRY_REQUIRE_SUCCESS';
export const LORRY_REQUIRE_FAILURE = 'LORRY_REQUIRE_FAILURE';

// Delete Lorry
export const INIT_DELETE_LORRY = 'INIT_DELETE_LORRY';
export const DELETE_LORRY_SUCCESS = 'DELETE_LORRY_SUCCESS';
export const DELETE_LORRY_FAILURE = 'DELETE_LORRY_FAILURE';

// Delete Lorry
export const INIT_GET_REQUEST_BOOKING = 'INIT_GET_REQUEST_BOOKING';
export const INIT_GET_REQUEST_BOOKING_SUCCESS =
  'INIT_GET_REQUEST_BOOKING_SUCCESS';
export const INIT_GET_REQUEST_BOOKING_SUCCESS_SENT =
  'INIT_GET_REQUEST_BOOKING_SUCCESS_SENT';
export const INIT_GET_REQUEST_BOOKING_SUCCESS_RECEIVED =
  'INIT_GET_REQUEST_BOOKING_SUCCESS_RECEIVED';
export const INIT_GET_REQUEST_BOOKING_FAILURE =
  'INIT_GET_REQUEST_BOOKING_FAILURE';

// Cancel Booking
export const INIT_CANCEL_BOOKING = 'INIT_CANCEL_BOOKING';
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS';
export const CANCEL_BOOKING_FAILURE = 'CANCEL_BOOKING_FAILURE';

// Uploading Aadhar/Pan/Gst
export const INIT_DOCUMENT_VERIFY = 'INIT_DOCUMENT_VERIFY';
export const DOCUMENT_UPLOAD_SUCCESS = 'DOCUMENT_UPLOAD_SUCCESS';
export const DOCUMENT_UPLOAD_FAILURE = 'DOCUMENT_UPLOAD_FAILURE';

// Getting the documents verification
export const INIT_DOCUMENT_VERIFICATION = 'INIT_DOCUMENT_VERIFICATION';
export const DOCUMENT_VERIFICATION_SUCCESS = 'DOCUMENT_VERIFICATION_SUCCESS';
export const DOCUMENT_VERIFICATION_FAILURE = 'DOCUMENT_VERIFICATION_FAILURE';

// Uploading the rc verification
export const INIT_RC_VERIFICATION = 'INIT_RC_VERIFICATION';
export const RC_VERIFICATION_SUCCESS = 'RC_VERIFICATION_SUCCESS';
export const RC_VERIFICATION_FAILURE = 'RC_VERIFICATION_FAILURE';

// Uploading the rc verification
export const INIT_QR_SCANNER = 'INIT_QR_SCANNER';
export const QR_SCANNER_SUCCESS = 'QR_SCANNER_SUCCESS';
export const QR_SCANNER_FAILURE = 'QR_SCANNER_FAILURE';

// Maps
export const FETCH_MAP_DATA_START = 'FETCH_MAP_DATA_START';
export const FETCH_MAP_DATA_SUCCESS = 'FETCH_MAP_DATA_SUCCESS';
export const FETCH_MAP_DATA_FAILURE = 'FETCH_MAP_DATA_FAILURE';

// create order
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

//Verify Payment
export const VERIFY_PAYMENT_REQUEST = 'VERIFY_PAYMENT_REQUEST';
export const VERIFY_PAYMENT_SUCCESS = 'VERIFY_PAYMENT_SUCCESS';
export const VERIFY_PAYMENT_FAILURE = 'VERIFY_PAYMENT_FAILURE';

// Complete Booking Document for Lorry Owner
export const COMPLETE_BOOKING_DOCUMENT_REQUEST =
  'COMPLETE_BOOKING_DOCUMENT_REQUEST';
export const COMPLETE_BOOKING_DOCUMENT_SUCCESS =
  'COMPLETE_BOOKING_DOCUMENT_SUCCESS';
export const COMPLETE_BOOKING_DOCUMENT_FAILURE =
  'COMPLETE_BOOKING_DOCUMENT_FAILURE';

// Transcations
export const FETCH_TRANSACTIONS_REQUEST = 'FETCH_TRANSACTIONS_REQUEST';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAILURE = 'FETCH_TRANSACTIONS_FAILURE';

// Genetate Token for GPS.js
export const FETCH_GPS_TOKEN_REQUEST = 'FETCH_GPS_TOKEN_REQUEST';
export const FETCH_GPS_TOKEN_SUCCESS = 'FETCH_GPS_TOKEN_SUCCESS';
export const FETCH_GPS_TOKEN_FAILURE = 'FETCH_GPS_TOKEN_FAILURE';

// Fetching GPS devices
export const FETCH_GPS_DEVICES_REQUEST = 'FETCH_GPS_DEVICES_REQUEST';
export const FETCH_GPS_DEVICES_SUCCESS = 'FETCH_GPS_DEVICES_SUCCESS';
export const FETCH_GPS_DEVICES_FAILURE = 'FETCH_GPS_DEVICES_FAILURE';

// Gps Websocket
export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
export const WEBSOCKET_DISCONNECT = 'WEBSOCKET_DISCONNECT';
export const WEBSOCKET_MESSAGE = 'WEBSOCKET_MESSAGE';
export const WEBSOCKET_ERROR = 'WEBSOCKET_ERROR';
export const WEBSOCKET_CLOSED = 'WEBSOCKET_CLOSED';
export const WEBSOCKET_RETRY = 'WEBSOCKET_RETRY';
export const UPDATE_DEVICES = 'UPDATE_DEVICES';
export const UPDATE_POSITIONS = 'UPDATE_POSITIONS';
export const UPDATE_EVENTS = 'UPDATE_EVENTS';

// GPS Address
export const FETCH_GPS_ADDRESS_REQUEST = 'FETCH_GPS_ADDRESS_REQUEST';
export const FETCH_GPS_ADDRESS_SUCCESS = 'FETCH_GPS_ADDRESS_SUCCESS';
export const FETCH_GPS_ADDRESS_FAILURE = 'FETCH_GPS_ADDRESS_FAILURE';

// GPS Summary
export const FETCH_SUMMARY_REPORT_REQUEST = 'FETCH_SUMMARY_REPORT_REQUEST';
export const FETCH_SUMMARY_REPORT_SUCCESS = 'FETCH_SUMMARY_REPORT_SUCCESS';
export const FETCH_SUMMARY_REPORT_FAILURE = 'FETCH_SUMMARY_REPORT_FAILURE';
