import {StyleSheet} from 'react-native';
import {
  textColor,
  GradientColor2,
  pageBackground,
  inputColor,
  white,
  titleColor,
  backgroundColorNew
} from '../../Color/color';

export default StyleSheet.create({
  viewDetailsOriginImg: {width: 20, height: 20},
  setFlex: {flex: 1},
  marginTopStyle: {marginTop: 15},
  truckNumViewStyle: {flexDirection: 'row', marginTop: 10, flexWrap: 'wrap'},
  truckNumTxtStyle: {minWidth: 120, color: titleColor},
  logDetailsTxt: {fontSize: 16, color: '#352422', fontWeight: 'bold'},
  viewDetailScrollView1: {marginVertical: 10},
  viewDetailScrollView2: {flexDirection: 'row', flexWrap: 'wrap'},
  viewDetailScrollView3: {flexDirection: 'row', marginTop: 10},
  viewDetailBtnStyle: {justifyContent: 'center', alignItems: 'center'},
  isFullScreenView: {
    flex: 0.5,
    padding: 10,
    paddingHorizontal: 20,
    elevation: 2,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  fromToText: {minWidth: 50, color: titleColor},
  notifContainer: {
    paddingHorizontal: 5,
    backgroundColor: '#FDFDFD',
    flex: 1,
  },
  notifFlatList: {marginTop: 10},
  noInternetContainer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: '#FFD7CC',
  },
  subContainer: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 30,
    paddingHorizontal: 20,
    paddingVertical: 15,
    flexDirection: 'row',
    width: '100%',
  },
  viewDetailContainer: {
    flex: 1,
    backgroundColor: '#bce2c5',
  },
  map: {
    flex: 1,
  },
  backButton: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  fullScreenButton: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: '#FFFFFF',
    zIndex: 1,
    elevation: 2,
    padding: 10,
    borderRadius: 30,
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  container: {
    backgroundColor: pageBackground,
    flex: 1,
    padding: 10,
  },
  webview: {
    flex: 1,
    marginTop: 10,
  },
  btnStyle: {
    borderWidth: 2,
    borderRadius: 8,
    backgroundColor: backgroundColorNew,
    borderColor: backgroundColorNew,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    width: '80%',
    alignSelf: 'center',
  },
  btnText: {
    fontSize: 16,
    color: textColor,
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
  },
  MainContainer: {
    backgroundColor: white,
    flex: 1,
  },
  companyDetailsBtn: {
    flexDirection: 'row',
    borderRadius: 8,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    flexDirection: 'row',
    borderRadius: 28,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  touchStyle: {
    marginLeft: 30,
    marginRight: 30,
    marginTop: 30,
  },
  chooseOptionBox: {
    backgroundColor: 'rgba(0,0,0, 0.5)',
    flex: 1,
  },
  chooseOptionBoxView: {
    backgroundColor: '#FFFFFF',
    padding: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    position: 'absolute',
    bottom: 0,
    marginTop: 200,
  },
  companyDetailsTouchStyle: {
    marginLeft: 20,
    marginRight: 20,
    marginTop: 20,
  },
  unSelectItem: {
    padding: 18,
    backgroundColor: inputColor,
    borderRadius: 8,
    margin: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inconvContainer: {
    flex: 1,
    backgroundColor: '#FFFDFD',
    justifyContent: 'center',
    alignItems: 'center',
    // borderWidth: 1,
    // marginTop: 60,
  },
  containerChild1: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    width: '100%',
    // borderWidth: 1,
    paddingBottom: 30,
  },
  textStyle: {
    color: '#352422',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorText: {
    textAlign: 'center',
    color: 'red',
  },
  modalTopLine: {
    height: 5,
    backgroundColor: '#E2E2E2',
    width: '30%',
    position: 'absolute',
    borderRadius: 50,
    top: 0,
    alignSelf: 'center',
    marginVertical: 10,
  },
  findButtonContainer: {
    flexDirection: 'row',
    borderRadius: 10,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  findButtonText: {
    fontSize: 14,
    color: white,
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
  },
  imageStyle: {
    width: 70,
    height: 40,
    alignSelf: 'center',
    marginBottom: 5,
  },
  protypeimageStyle: {
    width: 60,
    height: 60,
    alignSelf: 'center',
    marginBottom: 5,
  },
  checkIconStyle: {position: 'absolute', top: 5, left: 5},
  flatListStyle: {marginTop: 12, marginBottom: 20},
  flatListLang: {
    marginTop: 60,
    alignSelf: 'center',
    maxHeight: '60%',
    borderWidth: 1,
  },
  buttonTitile: {
    fontWeight: 'bold',
    color: textColor,
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  searchLocationView: top => ({
    elevation: 2,
    zIndex: 10,
    borderRadius: 10,
    maxHeight: 250,
    backgroundColor: white,
    position: 'absolute',
    width: '100%',
    left: 20,
    top: top,
  }),
  gridbox: {
    height: 120,
    width: 124,
    margin: 10,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectItem: {
    padding: 18,
    margin: 10,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  truckTypeItem: {
    // width: 60,
    height: 45,
    paddingHorizontal: 10,
    minWidth: 45,
    marginRight: 10,
    marginBottom: 10,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f19e72',
  },
  TyuckTypeUnSelectItem: {
    height: 45,
    paddingHorizontal: 10,
    minWidth: 45,
    marginRight: 10,
    marginBottom: 10,
    backgroundColor: inputColor,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  truckCapacityItem: {
    width: 110,
    height: 45,
    marginRight: 10,
    marginBottom: 10,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  TyuckCapacityUnSelectItem: {
    width: 110,
    height: 45,
    marginRight: 10,
    marginBottom: 10,

    backgroundColor: inputColor,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  unSelectItem: {
    padding: 18,
    backgroundColor: inputColor,
    borderRadius: 8,
    margin: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gridGreyBox: {
    height: 120,
    width: 124,
    margin: 10,
    backgroundColor: inputColor,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#ddd',
    borderWidth: 3,
  },
  label: {
    fontWeight: '700',
    fontSize: 18,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  ItemView: {marginTop: 30},
  CameraText: {
    fontSize: 15,
    color: 'black',
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Medium',
  },
  lorryLabel: {
    fontWeight: '700',
    fontSize: 15,
    color: 'black',
    fontFamily: 'PlusJakartaSans-Medium',
  },
  signupBackground: {
    padding: 20,
    backgroundColor: pageBackground,
    justifyContent: 'center',
    marginTop: 25,
    alignItems: 'center',
  },
  companyDetailsSignupBackground: {
    padding: 10,
    backgroundColor: pageBackground,
    justifyContent: 'center',
    marginTop: 10,
    alignItems: 'center',
    // borderWidth: 1,
  },
  text: {color: '#000000', fontFamily: 'PlusJakartaSans-Bold', fontSize: 18},
  bottomText: {
    opacity: 0.8,
    marginTop: 3,
    color: '#000000',
    fontFamily: 'PlusJakartaSans-Regular',
    fontSize: 16,
  },
  WelcomeTruckTitle: {
    fontWeight: '700',
    color: 'black',
    fontSize: 22,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Medium',
  },
  editProfileTitle: {
    fontWeight: '700',
    color: titleColor,
    fontSize: 20,
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  gridText: {
    fontSize: 12,
    color: 'white',
    textAlign: 'center',
    // marginTop: 5,
    // paddingBottom: 5,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  gridGreyText: {
    fontSize: 12,
    color: titleColor,
    // marginTop: 5,
    // paddingBottom: 5,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  profileImgContainer: {
    height: 80,
    width: 80,
    marginTop: 30,
    borderRadius: 40,
  },
  editProfileContainer: {
    height: 80,
    width: 80,
    borderRadius: 40,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  profileImgEdit: {
    height: 25,
    width: 25,
    backgroundColor: GradientColor2,
    borderRadius: 40,
    position: 'absolute',
    bottom: -5,
    left: 30,
    borderWidth: 1,
    borderColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  companyDetailsProfileImgEdit: {
    height: 25,
    width: 25,
    // backgroundColor: GradientColor2,
    backgroundColor: backgroundColorNew,
    borderRadius: 40,
    position: 'absolute',
    bottom: -5,
    left: 30,
    borderWidth: 1,
    borderColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileImg: {
    height: 80,
    width: 80,
    borderRadius: 40,
  },
  cameraIcons: {
    height: 50,
    width: 50,
  },
  paddingStyle: {
    padding: 20,
  },
  companyDetailsPaddingStyle: {
    padding: 10,
    // borderWidth: 1,
  },
  companyDetailsView: {
    marginBottom: 30
  },
  modalView: {
    backgroundColor: '#FFFFFF',
    padding: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    position: 'absolute',
    bottom: 0,
    marginTop: 200,
  },
  editModalView: {
    backgroundColor: '#FFFFFF',
    padding: 10,
    borderRadius: 8,
    margin: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    marginTop: 60,
  },
  imagePickerView: {flexDirection: 'row', justifyContent: 'space-around'},
});
