import {StyleSheet} from 'react-native';
import {
  textColor, 
  GradientColor1,
  GradientColor2,
  GradientColor3,
  PrivacyPolicy,
  black,
  titleColor
} from '../../Color/color';

export default StyleSheet.create({
  lottieViewStyle: {
    height: 600,
    width: 200,
  },
  fullScreenContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  chooseOptionsView1: {
    backgroundColor: '#FFFFFF',
    padding: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    position: 'absolute',
    bottom: 0,
    marginTop: 200,
  },
  chooseOptionsView2: {
    flexDirection: 'row', 
    justifyContent: 'space-around'
  },
  setFlex: {flex: 1},
  centeredText: {
    justifyContent: 'center', 
    alignItems: 'center'
  },
  fromAadharView: {
    flexDirection: 'row',
    borderWidth: 1.5,
    borderColor: GradientColor3,
    borderStyle: 'dotted',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 200,
  },
  touchableOpacityStyle: {
    width: '100%', 
    height: '100%', 
    flex: 1
  },
  cardDetailsView: {
    backgroundColor: '#AFAFAF',
    width: 1.5,
    height: '100%',
    marginHorizontal: 10,
  },
  backTextView: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginTop: 5,
  },
  backTextStyle: {textAlign: 'center'},
  docUploadLoading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  frontTxt: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginTop: 5,
  },
  docPickerView: {
    borderWidth: 1,
    borderRadius: 8,
    borderColor: '#ddd',
    marginBottom: 10,
  },
  setPrivacyPolicy: {color: PrivacyPolicy},
  frontImgView: {
    flexDirection: 'row',
    borderWidth: 1.5,
    borderColor: GradientColor3,
    borderStyle: 'dotted',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 200,
  },
  touchableOpacityView: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginTop: 5,
  },
  closeButton: {
    position: 'absolute',
    right: 10,
    top: 10,
    zIndex: 10,
    color: titleColor,
  },
  mainContainer: {
    margin: '3%',
    flex: 1,
    borderRadius: 10,
    backgroundColor: 'white',
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    // padding: 30,
    // backgroundColor: "#fff",
    // borderRadius: 10,
  },
  congratsText: {
    fontSize: 30,
    marginBottom: 10,
    marginTop: 20,
    fontWeight: '700',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  verifyText: {
    fontSize: 18,
    color: titleColor,
    marginBottom: 20,
    fontWeight: '600',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  cardContainer: {
    width: '100%',
    borderWidth: 2,
    borderRadius: 8,
    borderColor: GradientColor1,
    borderStyle: 'dotted',
    padding: 5,
    marginBottom: 30,
  },
  info: {
    marginTop: 10,
    alignItems: 'center',
  },
  searchLoadButton: {
    backgroundColor: '#FFA500',
    padding: 15,
    width: '100%',
    borderRadius: 5,
    alignItems: 'center',
    marginBottom: 10,
  },
  statusButtonContainer: {
    borderWidth: 2,
    borderColor: GradientColor3,
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    // marginTop: 10,
    // marginBottom: 20,
    width: '50%',
    alignSelf: 'center',
  },

  statusButtonText: {
    color: GradientColor3,
    fontWeight: '700',
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  statusButtonTextStyle: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  statusButtonstyle: status => ({
    backgroundColor: status ? GradientColor3 : PrivacyPolicy,
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    alignSelf: 'center',
  }),

  card: {
    backgroundColor: '#fff',
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
    paddingBottom: 20,
    alignItems: 'center',
    elevation: 1,
    // shadowColor: "#000",
    // shadowOffset: { width: 0, height: 1 },
    // shadowOpacity: 0.22,
    // shadowRadius: 2.22,
  },
  childCard: {
    flexDirection: 'row',
    backgroundColor: '#FFF5EA',
    borderRadius: 5,
    paddingVertical: 10,
    alignItems: 'center',
    // borderWidth: 1,
  },
  statusImage: {
    width: 80,
    height: 60,
    resizeMode: 'contain',
  },
  details: {
    marginLeft: 20,
    flex: 1,
    justifyContent: 'center',
    fontSize: 14,
    color: '#555',
    alignItems: 'flex-start',
    // borderWidth: 1,
  },
  statusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  truckNumber: {
    fontSize: 18,
    marginRight: 10,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  truckType: {
    fontSize: 16,
    color: PrivacyPolicy,
    fontWeight: '600',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  specs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 5,
    width: '90%',
    // borderWidth: 1,
  },
  specsText: {
    fontSize: 14,
    color: PrivacyPolicy,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  horizontalLine: {
    backgroundColor: '#ddd',
    height: 1,
    margin: 5,
  },
  verticalLine: {
    backgroundColor: '#ddd',
    width: 2,
    marginHorizontal: 10,
  },
  text: {
    marginVertical: 30,
    marginHorizontal: 20,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 18,
    color: PrivacyPolicy,
  },
  boldText: {
    color: black,
    fontWeight: '700',
  },

  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#FFFDFD',
  },
  qrContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  flashlightButton: {
    position: 'absolute',
    bottom: 50,
    // backgroundColor: '#4d4d4d',
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 8,
    padding: 10,
    borderWidth: 2,
    borderColor: PrivacyPolicy,
  },
  commonToolbar: {
    marginTop: 10,
    marginBottom: 30,
  },
  otpSection: {
    flex: 1,
  },
  otpLabel: {
    fontSize: 18,
    marginBottom: 10,
    fontWeight: '700',
    fontFamily: 'PlusJakartaSans-Bold',
    color: titleColor,
  },
  otpInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    padding: 10,
    fontSize: 16,
    marginBottom: 10,
    color: titleColor,
  },
  resendBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  manualVerification: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#e1eedf',
    borderRadius: 5,
  },
  manualText: {
    fontSize: 16,
    flex: 1,
    fontWeight: '700',
    fontFamily: 'PlusJakartaSans-Bold',
    color: titleColor,
  },
  manualBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#119500',
    backgroundColor: '#119500',
    borderRadius: 20,
    padding: 10,
    alignItems: 'center',
  },
  resendContainer: {
    borderWidth: 1,
    paddingHorizontal: 8,
    borderRadius: 5,
    borderColor: '#ddd',
  },
  resendText: {
    textDecorationLine: 'underline',
    color: GradientColor3,
    fontWeight: '600',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  counter: {
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  imageUploader: {
    borderWidth: 2,
    borderColor: GradientColor3,
    borderStyle: 'dotted',
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    height: 200,
    marginTop: 15,
    marginBottom: 8,
  },
  uploadText: {
    fontSize: 14,
    color: '#888',
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  smallText: {
    fontSize: 12,
    // marginBottom: 20,
    color: '#888',
  },
  label: {
    fontSize: 15,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  buttonTextStyle: {
    color: textColor,
    fontWeight: '700',
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  buttonstyle: {
    flexDirection: 'row',
    borderRadius: 8,
    height: 50,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    width: '60%',
    // marginBottom: 20,
  },
  buttonContainer: {
    borderWidth: 2,
    borderColor: GradientColor3,
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 20,
    width: '100%',
    alignSelf: 'center',
  },
  buttonText: {
    color: GradientColor3,
    fontWeight: '700',
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  focusBorder: {
    position: 'absolute',
    width: 300,
    height: 300,
    // borderWidth: 5,
  },
  cornerTopLeft: {
    position: 'absolute',
    // left: 20,
    // top: 20,
    width: 50,
    height: 50,
    borderTopWidth: 5,
    borderLeftWidth: 5,
    borderColor: '#FFFFFF',
    borderTopLeftRadius: 20,
  },
  cornerTopRight: {
    position: 'absolute',
    right: 0,
    // top: 20,
    width: 50,
    height: 50,
    borderTopWidth: 5,
    borderRightWidth: 5,
    borderColor: '#FFFFFF',
    borderTopRightRadius: 20,
  },
  cornerBottomLeft: {
    position: 'absolute',
    // left: 20,
    bottom: 0,
    width: 50,
    height: 50,
    borderBottomWidth: 5,
    borderLeftWidth: 5,
    borderColor: '#FFFFFF',
    borderBottomLeftRadius: 20,
  },
  cornerBottomRight: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 50,
    height: 50,
    borderBottomWidth: 5,
    borderRightWidth: 5,
    borderColor: '#FFFFFF',
    borderBottomRightRadius: 20,
  },
  modalContainer: {
    backgroundColor: 'rgba(0,0,0, 0.5)',
    flex: 1,
  },
  modalChildContainer: {
    backgroundColor: '#FFFFFF',
    padding: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    position: 'absolute',
    bottom: 0,
    marginTop: 200,
  },
  iconBox: {justifyContent: 'center', alignItems: 'center'},
  optionBox: {flexDirection: 'row', justifyContent: 'space-around'},
  seperatorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  halfHorizontalLine: {
    backgroundColor: titleColor,
    height: 2,
    flex: 1,
  },
  orText: {
    fontSize: 14,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
    marginHorizontal: 5,
  },
  paramBox: {
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    backgroundColor: '#FFEBE6',
  },
  RCText: {
    color: titleColor,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  imageBox: {marginTop: 20, flex: 1},
  borderLineContainer: {
    flexDirection: 'row',
    borderWidth: 1.5,
    borderColor: GradientColor3,
    borderStyle: 'dotted',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 15,
    flex: 1,
  },
  innerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginTop: 5,
  },

  //
  activityIndicator: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityIndicatorBox: {width: '100%', height: '100%', flex: 1},
});
