import {StyleSheet, StatusBar} from 'react-native';
import {
  GradientColor2,
  GradientColor3,
  PrivacyPolicy,
  pageBackground,
  titleColor,
  textColor,
  inputColor,
} from '../../../Color/color';

export default StyleSheet.create({
  whatsappContainer: {flex: 1},
  whatsappView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingTop: 30,
    backgroundColor: pageBackground,
  },
  whatsappText: {
    fontSize: 18,
    fontWeight: '700',
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  container: {
    flex: 1,
    backgroundColor: '#FDFDFD',
  },
  profileContainer: {flex: 1},
  profileImg: (hei, wid) => ({
    height: hei / 2.5, width: wid
  }),
  profileDetailsView: {
    flex: 1, 
    marginLeft: 17, 
    justifyContent: 'center'
  },
  profileRateVerifyOutView: {flexDirection: 'row', marginTop: 7},
  profileRateVerifyInView: {flexDirection: 'row'},
  profileScrollView: {flex: 1, marginBottom: 60},
  allTermsContainer: {
    backgroundColor: pageBackground,
    flex: 1,
    padding: 10,
  },
  webview: {
    flex: 1,
    marginTop: 10,
  },
  flatListContainer: {
    padding: 10,
  },
  card: {
    backgroundColor: 'white',
    borderRadius: 5,
    paddingVertical: 15,
    paddingHorizontal: 10,
    marginBottom: 10,
    elevation: 2,
    flexDirection: 'row',
  },
  addressContainer: {
    flex: 1,
    paddingStart: 10,
  },
  address: {
    fontSize: 12,
    color: titleColor,
    marginTop: 4,
    fontFamily: 'PlusJakartaSans-Medium',
    lineHeight: 18,
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 10,
  },
  editText: {
    fontSize: 12,
    color: 'green',
    marginLeft: 10,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  actionText: {
    fontSize: 12,
    color: 'red',
    marginLeft: 5,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  touchStyle: {
    marginVertical: 20,
    width: '60%',
    alignSelf: 'center',
  },
  buttonStyle: {
    flexDirection: 'row',
    borderRadius: 8,
    padding: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonTextStyle: {
    color: textColor,
    fontWeight: '700',
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  iconBox: {
    borderRightWidth: 2,
    paddingEnd: 5,
    paddingTop: 10,
    borderColor: '#707070',
    justifyContent: 'flex-start',
  },
  actionBtns: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 15,
    justifyContent: 'center',
  },
  noAddressContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noAddressText: {
    fontSize: 16,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  flexContainer: {
    flex: 1,
  },
  statusBar: {
    height: StatusBar.currentHeight,
    width: '100%',
  },
  gradient: {
    flex: 1,
  },
  iconContainer: {
    flexDirection: 'row',
    width: '100%',
    marginVertical: 20,
    justifyContent: 'space-evenly',
  },
  contactUsButtonStyle: {
    flexDirection: 'row',
    borderRadius: 8,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 20,
  },
  textStyle: {
    fontWeight: 'bold',
    color: textColor,
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  label: {
    fontSize: 15,
    color: titleColor,
    marginTop: 20,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  formContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: 20,
  },
  button: {
    flexDirection: 'row',
    borderRadius: 8,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonTitile: {
    fontWeight: 'bold',
    color: textColor,
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  editProfileLabel: {
    fontWeight: '700',
    fontSize: 18,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  CameraText: {
    fontSize: 15,
    color: 'black',
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Medium',
  },
  editProfileTitle: {
    fontWeight: '700',
    color: titleColor,
    fontSize: 20,
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  editProfileContainer: {
    height: 80,
    width: 80,
    borderRadius: 40,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  profileImgEdit: {
    height: 25,
    width: 25,
    backgroundColor: GradientColor2,
    borderRadius: 40,
    position: 'absolute',
    bottom: -5,
    left: 30,
    borderWidth: 1,
    borderColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileImg: {
    height: 80,
    width: 80,
    borderRadius: 40,
  },
  paddingStyle: {
    padding: 20,
  },
  editModalView: {
    backgroundColor: '#FFFFFF',
    padding: 10,
    borderRadius: 8,
    margin: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    marginTop: 60,
  },
  mobileTxt: {
    backgroundColor: inputColor,
    marginTop: 12,
    borderRadius: 8,
    padding: 15,
    color: PrivacyPolicy,
  },
  closeBtnView: {alignItems: 'flex-end'},
  galleryView: {justifyContent: 'center', alignItems: 'center'},
  cammeraView: {justifyContent: 'center', alignItems: 'center'},
  allEditBtnView: {flexDirection: 'row', justifyContent: 'space-around'},
  editProfileModalStyle: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0, 0.5)',
    justifyContent: 'center',
  },
  chooseOpnOutterView: {
    backgroundColor: 'rgba(0,0,0, 0.9)',
    flex: 1,
  },
  chooseOtnInnerView: {
    backgroundColor: '#FFFFFF',
    padding: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    position: 'absolute',
    bottom: 0,
    marginTop: 200,
  },
  editRemoveImg:{height: 35, width: 40},
  guideBackgroundView: {
    padding: 10,
    backgroundColor: '#FFFDFD',
    flex: 1,
  },
  header: {
    color: '#808080',
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize: 16,
  },
  callSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    backgroundColor: '#FFF5F2',
    borderColor: '#EF4D23',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 50,
  },
  phoneNo: {
    color: '#808080',
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize: 14,
    marginLeft: 10,
  },
  callBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: '#FFFFFF',
    elevation: 2,
    marginBottom: 10,
    marginHorizontal: 1,
    paddingHorizontal: 5,
    paddingVertical: 20,
    borderRadius: 10,
  },
  itemContainer: {
    borderRadius: 8,
    marginBottom: 10,
    marginHorizontal: 1,
    padding: 10,
  },
  category: {
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-Bold',
    marginRight: 15,
    color: '#808080',
  },
  topic: {
    fontSize: 14,
    textAlign: 'justify',
    fontFamily: 'PlusJakartaSans-Medium',
    lineHeight: 18 * 1.2,
    marginTop: 10,
    color: PrivacyPolicy,
  },
  arrow: {
    position: 'absolute',
    top: 15,
    right: 5,
  },
  guideHorizontalLine: {
    backgroundColor: '#AFAFAF', 
    height: 1, 
    marginBottom: 10
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    width: '90%',
    paddingHorizontal: 10,
    left: 15,
    borderRadius: 20,
    borderColor: PrivacyPolicy,
  },
  headerSearchInput: {
    flex: 1,
    height: 40,
  },
  searchButton: {
    top: 2,
  },
  colotss: {color: PrivacyPolicy},
  walletContainer: {
    // paddingHorizontal: 20,
    backgroundColor: pageBackground,
    flex: 1,
  },
  box: {
    backgroundColor: 'white',
    padding: 15,
    elevation: 2,
    borderRadius: 8,
    marginTop: 20,
    marginHorizontal: 10,
  },
  texts: {
    color: PrivacyPolicy,
    fontFamily: 'PlusJakartaSans-Regular',
    fontSize: 12,
  },
  walletText: {
    fontFamily: 'PlusJakartaSans-SemiBold',
    color: titleColor,
    fontSize: 20,
  },
  walletHorizontalLine: {
    height: 1,
    backgroundColor: '#E7E7E7',
    marginVertical: 10,
  },
  topupWallet: {
    color: PrivacyPolicy,
    marginTop: 10,
    marginBottom: 10,
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Regular',
  },
  dateText: {
    color: PrivacyPolicy,
    fontSize: 12,
    marginTop: 5,
    fontFamily: 'PlusJakartaSans-Regular',
  },
  inputContainer: {
    height: 50,
    borderRadius: 4,
    borderColor: '#E7E7E7',
    paddingLeft: 10,
    paddingRight: 10,
    borderWidth: 1,
    // marginBottom: 10,
    minWidth: 150,
  },
  textInput: {
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize: 15,
    width: '100%',
    color: titleColor,
  },
  renderItemStyle: {
    flexShrink: 1,
    backgroundColor: '#fffffa',
    shadowColor: GradientColor3,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 2,
    width: 100,
    padding: 8,
    margin: 5,
    borderRadius: 20,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  suggest: {
    fontFamily: 'PlusJakartaSans-Medium',
    color: titleColor,
  },
  walletButtonStyle: {
    flexDirection: 'row',
    borderRadius: 8,
    height: 50,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  walletTextStyle: {
    color: textColor,
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  requestButtonContainer: {
    borderWidth: 1,
    borderRadius: 5,
    borderColor: GradientColor3,
    paddingHorizontal: 15,
    paddingVertical: 8,
  },
  gradientButtonText: {
    fontSize: 12,
    color: GradientColor3,
    fontFamily: 'PlusJakartaSans-SemiBold',
    textAlign: 'center',
  },
  repeatView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    padding: 15,
    elevation: 2,
    borderRadius: 8,
    marginVertical: 10,
    marginHorizontal: 15,
    alignItems: 'center',
  },
  deductionCard: {
    flexDirection: 'column',
    // alignItems: 'center',
    // justifyContent: 'space-between',
    backgroundColor: 'white',
    padding: 15,
    elevation: 2,
    borderRadius: 8,
    marginVertical: 10,
    marginHorizontal: 15,
  },
  tabView: {
    flex: 1,
    marginTop: 10,
    backgroundColor: '#FFFDFD',
  },
  paymentText: {
    fontFamily: 'PlusJakartaSans-SemiBold',
    color: 'green',
  },
  rowdirection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  textDetailStyle: {
    color: titleColor,
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  walletVerticalLine: {
    backgroundColor: PrivacyPolicy,
    width: 2,
    marginHorizontal: 10,
    height: '100%',
  },
  loacationBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  circleDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'green',
    marginRight: 5,
  },
  squareDot: {
    width: 8,
    height: 8,
    backgroundColor: 'red',
    marginRight: 5,
  },
  loactionTextView: {
    flexDirection: 'row',
    // justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    flexWrap: 'wrap',
  },
  locationText: {
    // borderWidth: 1,
    color: titleColor,
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Regular',
  },
  inputContainerBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  backgroundView: {
    paddingHorizontal: 20,
    paddingBottom: 5,
    backgroundColor: '#FFFDFD',
    flex: 1,
    // borderWidth: 1,
  },
  menuIconView: {
    backgroundColor: pageBackground,
    width: 35,
    height: 35,
    margin: 1,
    elevation: 2,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontWeight: '700',
    color: titleColor,
    fontSize: 20,
    // width: "80%",
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
  },
  headerView: {
    // flexDirection: "row",
    // width: "100%",
    // justifyContent: "center",
    height: 50,
    // alignItems: "center",
  },
  profileTitle: {
    fontSize: 16,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
    fontWeight: '700',
  },
  subTitle: {
    fontSize: 13,
    color: PrivacyPolicy,
    fontWeight: '700',
    fontFamily: 'PlusJakartaSans-Regular',
  },
  ratingTextStyle: {
    // marginTop: 25,
    // fontSize: 14,
    // fontWeight: "500",
    // color: titleColor,
    color: '#F0C200',
    fontWeight: '700',
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  bigImageStyle: {
    // backgroundColor: '#000000',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    flex: 1,
  },
  closeIcon: {position: 'absolute', right: 10, top: 10},
  imageContainer: {
    width: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileView: {
    flexDirection: 'row',
    borderWidth: 1,
    padding: 15,
    borderRadius: 8,
    borderColor: '#ddd',
    elevation: 2,
    backgroundColor: pageBackground,
    marginBottom: 10,
  },
  verticalLine: {
    backgroundColor: '#ddd',
    width: 1,
    // marginLeft: 10,
    marginHorizontal: 5,
  },
  horizontalLine: {
    backgroundColor: '#ddd',
    height: 1,
    margin: 5,
  },
  dashboardHeaderVerifiedTitle: color => ({
    fontSize: 12,
    color: color ? 'green' : GradientColor2,
    fontFamily: 'PlusJakartaSans-SemiBold',
    marginLeft: 5,
    fontWeight: '700',
  }),
  pressable: {justifyContent: 'center'},
  buttonContainer: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fffaed',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    width: '48%',
    alignSelf: 'center',
  },
  buttonText: {
    color: titleColor,
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-ExtraBold',
    marginLeft: 10,
  },
  buttonView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  section: {
    marginVertical: 10,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  sectionHeaderText: {
    fontWeight: '700',
    color: titleColor,
    fontSize: 18,
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
    marginLeft: 10,
  },
  userDetails: {
    marginTop: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    elevation: 2,
    backgroundColor: pageBackground,
    padding: 10,
  },
  detailItem: {
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detailText: {
    fontSize: 16,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
    fontWeight: '700',
    marginLeft: 10,
  },
  flexDirection: {flexDirection: 'row'},
  appVersionView: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  appVersionText: {
    fontWeight: '500',
    color: titleColor,
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  percentageBarView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  rightArrowView: {
    marginLeft: 'auto',
    elevation: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
  },
});
