import {StyleSheet} from 'react-native';
import {
  GradientColor2,
  GradientColor3,
  PrivacyPolicy,
  pageBackground,
  textColor,
  titleColor,
  white,
} from '../../Color/color';

export default StyleSheet.create({
  indicatorStyle: {
    backgroundColor: GradientColor2,
    height: 4,
    // borderRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  tabBarStyle: {
    backgroundColor: pageBackground,
    borderColor: GradientColor2,
    borderRadius: 7,
    elevation: 2,
    margin: 10,
  },
  touchableOpacityStyles: {flex: 1, overflow: 'hidden'},
  routeNameGray: {color: 'grey'},
  routeNameBlack: {color: 'black'},
  // MyTabBar
  tabsContainer: {
    flexDirection: 'row',
    margin: 10,
    backgroundColor: '#E2E2E2',
    borderRadius: 8,
    padding: 3,
    // borderWidth: 1,
  },
  iconTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    gap: 8,
    // borderWidth: 1,
  },
  tabBgColor: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'white',
    borderRadius: 5,
    // borderWidth: 1,
  },
  tabView: {flex: 1, marginTop: 10},
  requestKeyboardAvoidView: {flex: 1, backgroundColor: '#FFFDFD'},
  DashboardHeaderView: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    elevation: 5,
    maxHeight: 60,
    padding: 10,
    backgroundColor: 'white',
    zIndex: 9999,
  },
  lottieView: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 100,
  },
  lottieText: {
    fontSize: 18,
    color: PrivacyPolicy,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  lottieStyle: {height: 250, width: 250},

  //
  card: {
    borderRadius: 8,
    elevation: 2,
    backgroundColor: '#FFFFFF',
    padding: 10,
    marginBottom: 10,
    marginTop: 10,
    marginLeft: 5,
    marginRight: 5,
  },
  headerView: {flexDirection: 'row'},
  image: {height: 60, width: 60, borderRadius: 5},
  dot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'green',
  },
  square: {
    width: 7,
    height: 7,
    borderRadius: 1,
    backgroundColor: 'red',
  },
  routeInfo: {
    flex: 1,
    marginLeft: 20,
  },
  routeTextContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textHeading: {
    // minWidth: 100,
    marginLeft: 10,
    color: PrivacyPolicy,
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  routeText: {
    flex: 1,
    color: titleColor,
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-SemiBold',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  horizontalLine: {backgroundColor: '#AFAFAF', height: 1, marginVertical: 10},
  verticalLine: {backgroundColor: '#AFAFAF', width: 1, marginHorizontal: 10},

  smallImageHeaderTitle: {
    fontSize: 15,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  point: {
    height: 8,
    width: 8,
    backgroundColor: PrivacyPolicy,
    borderRadius: 4,
    marginRight: 20,
    marginLeft: 10,
  },
  verifyTruck: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 20,
    borderColor: '#ccc',
    paddingVertical: 3,
    paddingHorizontal: 20,
    marginRight: 10,
    elevation: 1,
    backgroundColor: white,
  },
  dashboardHeaderVerifiedTitle: {
    fontSize: 12,
    color: GradientColor2,
    fontFamily: 'PlusJakartaSans-SemiBold',
    marginLeft: 5,
  },
  rowdirection: {flexDirection: 'row', alignItems: 'center'},
  buttonStyle: {
    flexDirection: 'row',
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 20,
  },
  textStyle: {
    color: textColor,
    fontSize: 13,
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
  },
  declineButton: {
    borderWidth: 2,
    borderRadius: 5,
    borderColor: GradientColor3,
  },
  declineButtonText: {
    fontSize: 13,
    color: GradientColor3,
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  CallButton: {
    borderWidth: 1,
    borderColor: '#ddd',
    elevation: 2,
    backgroundColor: '#ffffff',
    padding: 3,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
