import {StyleSheet} from 'react-native';
import {
  GradientColor2,
  GradientColor3,
  PrivacyPolicy,
  pageBackground,
  textColor,
  titleColor
} from '../../Color/color';

export default StyleSheet.create({ 
    statusChangeScreenModalView: {
        marginTop: '25%',
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        borderTopRightRadius: 20,
        borderTopLeftRadius: 20,
        backgroundColor: pageBackground,
        padding: 10,
      },
      negoFullScreenContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.2)',
      },
      screenModalView: {
        marginTop: '30%',
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        borderTopRightRadius: 20,
        borderTopLeftRadius: 20,
        backgroundColor: pageBackground,
      },
      negoCenteredView: {
        flex: 1,
        // justifyContent: "center",
        alignItems: 'center',
        marginTop: '15%',
      },
      horizontalLine: {backgroundColor: '#AFAFAF', height: 1, marginVertical: 10},
      verticalLine: {
        backgroundColor: '#AFAFAF',
        width: 2,
        marginHorizontal: 15,
        height: '100%',
      },
      rowdirection: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
      },
      textStyle: {
        color: PrivacyPolicy,
        fontSize: 14,
        fontFamily: 'PlusJakartaSans-Bold',
      },
      locationCard: {
        borderWidth: 1,
        borderColor: '#DBD7D7',
        padding: 10,
        borderRadius: 5,
      },
      priceText: {
        fontSize: 18,
        fontWeight: '700',
        color: titleColor,
        textAlign: 'center',
        marginVertical: 10,
        fontFamily: 'PlusJakartaSans-Bold',
      },
      priceInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
        borderWidth: 1,
        borderRadius: 5,
        borderColor: '#DBD7D7',
      },
      priceInput: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 2,
        paddingHorizontal: 10,
        width: '70%',
      },
      rupeeText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: titleColor,
        marginEnd: 5,
        fontFamily: 'PlusJakartaSans-Bold',
      },
      inputStyle: {
        fontSize: 16,
        textAlign: 'left',
        padding: 5,
        color: '#000',
        width: '75%',
      },
      priceType: {
        padding: 10,
        borderRadius: 5,
        fontWeight: 'bold',
      },
      btnBoxStyle: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
      },
      requestButtonContainer: {
        borderWidth: 2,
        borderRadius: 8,
        borderColor: GradientColor3,
      },
      gradientButtonText: {
        fontSize: 13,
        color: GradientColor3,
        fontFamily: 'PlusJakartaSans-Bold',
        textAlign: 'center',
      },
      buttonStyle: {
        flexDirection: 'row',
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 20,
        paddingHorizontal: 30,
        paddingVertical: 9,
        backgroundColor: GradientColor3,
      },
      findButtonText: {
        fontSize: 13,
        color: 'white',
        fontFamily: 'PlusJakartaSans-Bold',
        textAlign: 'center',
      },
      statusChangeCloseButton: {
        position: 'absolute',
        right: 20,
        color: titleColor,
      },
      closeButton: {
        position: 'absolute',
        right: 10,
        top: 10,
        zIndex: 10,
        color: titleColor,
      },
      header: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 10,
        paddingBottom: 10,
      },
      headerTitle: {
        color: titleColor,
        fontSize: 20,
        textAlign: 'center',
        justifyContent: 'center',
        fontFamily: 'PlusJakartaSans-Bold',
      },
      btnTextStyle: {
        color: textColor,
        fontSize: 16,
        fontFamily: 'PlusJakartaSans-Bold',
      },
    fullScreenContainer: {
        flex: 1,
        backgroundColor: '#FDFDFD',
        paddingVertical: 10,
        paddingHorizontal: 20,
        // borderWidth: 1,
    },
    centeredView: {
        flex: 1,
    },
    statusChangeCenteredView: {
        flex: 1,
        marginTop: '15%',
        // width: "100%",
        paddingVertical: 10,
      },
      body: {marginTop: 30},
      activeContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        margin: 10,
      },
      activeText: {fontSize: 18, fontWeight: '700', color: '#352422'},
      permitText: {fontSize: 16, fontWeight: '700', color: '#352422'},
      permitCountText: {fontSize: 16, fontWeight: '700', color: '#0089DE'},
      saveText: {
        color: textColor,
        fontWeight: '700',
        fontSize: 16,
        fontFamily: 'PlusJakartaSans-Bold',
      },
      saveButton: {
        flexDirection: 'row',
        borderRadius: 8,
        padding: 14,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
        width: '50%',
        alignSelf: 'center',
      },
      removeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
      },
      removeText: {
        marginRight: 20,
        color: GradientColor2,
        fontSize: 16,
        fontFamily: 'PlusJakartaSans-Bold',
      },
      noteText: {
        textAlign: 'center',
        marginHorizontal: 30,
        fontSize: 14,
        marginBottom: 15,
        color: titleColor,
        fontFamily: 'PlusJakartaSans-SemiBold',
      },
      statusChangeView: {
        flexDirection: 'row',
        justifyContent: 'space-between',
      },
    activeContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        margin: 10,
    },
    activeText: {fontSize: 18, fontWeight: '700', color: '#352422'},
    saveText: {
        color: textColor,
        fontWeight: '700',
        fontSize: 16,
        fontFamily: 'PlusJakartaSans-Bold',
    },
    saveButton: {
        flexDirection: 'row',
        borderRadius: 8,
        padding: 14,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
        width: '60%',
        alignSelf: 'center',
    },
    titleText: {
        fontSize: 15,
        color: titleColor,
        fontFamily: 'PlusJakartaSans-Bold',
    },
    multipleInputBox: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        //   borderWidth: 1,
    },
    multipleInputContainer: {minWidth: '48%'},
})