import {StyleSheet} from 'react-native';
import {
  PrivacyPolicy,
  textColor,
  GradientColor2,
  GradientColor3,
  pageBackground,
  inputColor,
  titleColor,
  back_color,
  loadingwalla,
} from '../../Color/color';
export default StyleSheet.create({
  phoneContainer: {
    width: '100%',
    height: 50,
    borderRadius: 8,
    marginTop: 8,
    borderColor: '#dddddd',
    borderWidth: 2,
  },
  signupBackground: {
    marginTop: 10,
    backgroundColor: pageBackground,
    height: '100%',
    // borderWidth: 1,
  },
  LoadingWalla: {
    color: loadingwalla,
    fontSize: 28,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  WelcomeTruckTitle: {
    color: titleColor,
    fontSize: 28,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Bold',
    // paddingHorizontal: 20,
    // borderWidth: 1,
  },
  signupTopTitle: {
    fontSize: 16,
    marginTop: 20,
    lineHeight: 20,
    maxWidth: 275,
    width: '100%',
    color: PrivacyPolicy,
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'PlusJakartaSans-SemiBold',
    // borderWidth: 1,
  },
  languageTitle: {
    fontSize: 18,
    marginTop: 20,
    lineHeight: 20,
    maxWidth: 275,
    width: '100%',
    color: PrivacyPolicy,
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  label: {
    fontWeight: '700',
    fontSize: 15,
    color: 'black',
    marginTop: 34,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  textInput: {
    paddingVertical: 0,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderStartWidth: 2,
    borderColor: '#ddd',
  },
  button: {
    flexDirection: 'row',
    borderRadius: 10,
    height: 50,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    width: '100%',
    // maxWidth: 255,
    marginTop: 22,
    marginBottom: 20,
  },
  backIconView: {
    width: 38,
    height: 38,
    elevation: 2,
    margin: 1,
    backgroundColor: 'white',
    marginBottom: 10,
    borderRadius: 8,

    justifyContent: 'center',
    alignItems: 'center',
  },

  buttonTitile: {
    fontWeight: 'bold',
    color: textColor,
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  policyTitle: {
    color: PrivacyPolicy,
    fontFamily: 'PlusJakartaSans-Medium',
    fontSize: 12,
    textAlign: 'center',
  },
  policyLinkTitle: activate => ({
    textDecorationLine: 'underline',
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 12,
    color: activate ? GradientColor3 : PrivacyPolicy,
  }),
  otpView: {width: '100%', height: 50, maxWidth: '85%', marginTop: 40},
  underlineStyleBase: {
    width: 60,
    height: 60,
    borderWidth: 1,
    fontSize: 22,
    borderRadius: 8,
    backgroundColor: inputColor,
    color: 'black',
    // borderWidth: 3,
    borderColor: '#ddd',
  },
  underlineStyleHighLighted: {
    backgroundColor: GradientColor2,
    color: pageBackground,
  },
  otpResendView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 32,
  },
  InputView: {
    backgroundColor: back_color,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 14,
    marginTop: 12,
    borderRadius: 8,
  },
  Input: {
    width: '80%',
    fontFamily: 'PlusJakartaSans-Medium',
    fontSize: 15,
    marginLeft: 8,
  },
  Container: {
    backgroundColor: '#FFFDFD',
    padding: 10,
    flex: 1,
  },
  SignupImage: {
    width: '100%',
    height: '40%',
    maxWidth: 255,
    alignSelf: 'center',
  },
  checkBoxContainer: {flexDirection: 'row', alignItems: 'center'},
  checkBoxStyle: {marginRight: 10},
  centerItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
});
