import {Dimensions, StyleSheet} from 'react-native';
import {
  PrivacyPolicy,
  textColor,
  GradientColor2,
  pageBackground,
  inputColor,
  titleColor,
  back_color,
  backgroundColorNew,
  textRed,
  grayColorOutline,
  arrowBtnFill,
  countryCode,
  phonePlaceholder,
  warningTxt,
  verifyOtpNumber,
} from '../../Color/color';

export default StyleSheet.create({
  flexs: {flex: 1},
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // borderWidth: 1,
  },
  hiddenButton: {
    minWidth: 140,
    overflow: 'hidden',
  },
  helpText: {
    // color: GradientColor2,
    color: backgroundColorNew,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  imageContainer: screenHeight => ({
    justifyContent: 'center',
    height: 0.45 * screenHeight,
  }),
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  phoneNumberInput: {
    // width: '100%',
    minHeight: 65,
    flexDirection: 'row',
    borderWidth: 1,
  },
  mbContainer: {
    width: '84%',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: grayColorOutline,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    // paddingHorizontal: 10,
    // paddingVertical: 1,
  },
  mbArrowContainer: {
    width: '16%',
    backgroundColor: arrowBtnFill,
    justifyContent: 'center',
    marginLeft: 2,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    // borderWidth: 1,
  },
  loadingWallaImg: {
    flex: 1,
    zIndex: 1,
  },
  phoneContainer: {
    width: '100%',
    height: 50,
    borderRadius: 8,
    marginTop: 8,
    borderColor: '#dddddd',
    borderWidth: 2,
  },
  innerContentContainer: {
    flex: 1,
  },
  LoadingWalla: {
    color: backgroundColorNew,
    fontSize: 28,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  mbcountryCode: {
    fontSize: 20,
    fontFamily: 'PlusJakartaSans-SemiBold',
    // marginRight: 5,
    color: countryCode,
  },
  mbdivider: {
    height: '100%',
    width: 1,
    backgroundColor: '#ccc',
    // marginHorizontal: 8,
  },
  mbphoneInput: {
    flex: 1,
    fontSize: 20,
    fontFamily: 'PlusJakartaSans-SemiBold',
    color: '#636363',
    borderWidth: 1,
    backgroundColor: 'white',
  },
  mbbutton: {
    alignItems: 'center',
  },
  WelcomeTruckTitle: {
    color: titleColor,
    fontSize: 28,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Bold',
    // paddingHorizontal: 20,
    // borderWidth: 1,
  },
  signupTextContainer: {
    justifyContent: 'space-between',
    alignContent: 'space-between',
  },
  signupWelcomeTitle: {
    fontSize: 16,
    color: textRed,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  signupTopTitle: {
    fontSize: 20,
    marginTop: 10,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  verifyOtpNumber: {
    color: verifyOtpNumber,
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize: 16,
  },
  languageTitle: {
    fontSize: 18,
    marginTop: 20,
    lineHeight: 20,
    maxWidth: 275,
    width: '100%',
    color: PrivacyPolicy,
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  label: {
    fontWeight: '700',
    fontSize: 15,
    color: 'black',
    marginTop: 34,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  textInput: {
    paddingVertical: 0,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderStartWidth: 2,
    borderColor: '#ddd',
  },
  button: {
    flexDirection: 'row',
    borderRadius: 10,
    height: 50,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    width: '100%',
    // maxWidth: 255,
    marginTop: 20,
    // marginBottom: 10,
  },
  backIconView: {
    width: 38,
    height: 38,
    elevation: 2,
    margin: 1,
    backgroundColor: 'white',
    marginBottom: 10,
    borderRadius: 8,

    justifyContent: 'center',
    alignItems: 'center',
  },

  buttonTitile: {
    fontWeight: 'bold',
    color: textColor,
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  policyTitle: {
    color: PrivacyPolicy,
    fontFamily: 'PlusJakartaSans-Regular',
    fontSize: 10,
    textAlign: 'center',
  },
  policyLinkTitle: activate => ({
    textDecorationLine: 'underline',
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 12,
    color: activate ? warningTxt : PrivacyPolicy,
    textAlign: 'center',
  }),
  otpResendView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // borderWidth: 1,
  },
  otpResendChild: {
    width: '50%',
    alignItems: 'flex-start',
    // borderWidth: 1,
  },
  otpResponseText: color => ({
    color: color ? 'green' : warningTxt,
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize: 12,
    marginLeft: 4,
  }),
  otpResponseView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpView: {},
  enterOtp: {
    fontFamily: 'PlusJakartaSans-ExtraBold',
    fontSize: 20,
    color: '#3F3F3F',
  },
  InputView: {
    backgroundColor: back_color,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 14,
    marginTop: 12,
    borderRadius: 8,
  },
  Input: {
    width: '80%',
    fontFamily: 'PlusJakartaSans-Medium',
    fontSize: 15,
    marginLeft: 8,
  },
  Container: {
    backgroundColor: '#FFFDFD',
    // padding: 10,
    flex: 1,
    // borderWidth: 1,
  },
  SignupImage: {
    width: '100%',
    height: '40%',
    maxWidth: 255,
    alignSelf: 'center',
  },
  centerItem: {
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonBox: {marginTop: 20, marginHorizontal: 55},
  timer: {
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  otpContainer: {
    flex: 1,
    // borderWidth: 1,
  },
  focusStick: {backgroundColor: 'white'},
  inputsContainer: {width: '100%'},
  pinCodeContainer: {
    width: 70,
    height: 70,
    fontSize: 22,
    borderRadius: 8,
    borderWidth: 0.5,
  },
  pinCodeText: {
    fontFamily: 'PlusJakartaSans-ExtraBold',
    fontSize: 32,
  },
  activePinCodeContainer: {
    backgroundColor: GradientColor2,
    color: pageBackground,
  },
  contentContainer: {
    flex: 2,
    paddingHorizontal: 25,
  },
  phoneNumberContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 65,
  },
  phoneInput: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '83%',
    height: 65,
    borderWidth: 0.5,
    borderColor: '#CCCCCC',
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    paddingLeft: 15,
    backgroundColor: '#F9F9F9',
    elevation: 1,
  },
  countryCode: {
    fontSize: 20,
    color: '#636363',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  separator: {
    height: '70%',
    borderLeftWidth: 0.5,
    marginHorizontal: 10,
    borderColor: '#595959',
  },
  phoneInputField: {
    flex: 1,
    fontSize: 20,
    color: '#636363',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  sendOtpButton: value => ({
    width: '16%',
    height: 65,
    backgroundColor: arrowBtnFill,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    opacity: value ? 1 : 0.5,
  }),
  phoneNumberWarningTxt: {
    color: warningTxt,
    fontSize: 12,
    textAlign: 'right',
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  phoneNumberWarningCtn: {
    height: 20,
    marginTop: 5,
  },
  policyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // marginTop: 10,
    flexWrap: 'wrap',
    // borderWidth: 1,
  },
});
