import {Dimensions, StyleSheet} from 'react-native';
import {
  PrivacyPolicy,
  textColor,
  GradientColor2,
  pageBackground,
  inputColor,
  titleColor,
  back_color,
  backgroundColorNew,
  textRed,
  grayColorOutline,
  arrowBtnFill,
  countryCode,
  phonePlaceholder,
  warningTxt,
  verifyOtpNumber,
} from '../../Color/color';

export default StyleSheet.create({
  flexs: {flex: 1},
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // borderWidth: 1,
  },
  hiddenButton: {
    minWidth: 140,
    overflow: 'hidden',
  },
  helpText: {
    // color: GradientColor2,
    color: backgroundColorNew,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  imageContainer: screenHeight => ({
    justifyContent: 'center',
    height: 0.45 * screenHeight,
  }),
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  phoneInputContainer: {
    zIndex: 5,
    marginLeft: 20,
  },
  phoneNumberInput: {
    width: '100%',
    minHeight: 75,
    flexDirection: 'row',
    marginTop: 30,
  },
  loadingWallaImg: {
    width: '100%',
    height: 340,
    overflow: 'hidden',
  },
  phoneContainer: {
    width: '100%',
    height: 50,
    borderRadius: 8,
    marginTop: 8,
    borderColor: '#dddddd',
    borderWidth: 2,
  },
  signupBackground: {
    backgroundColor: pageBackground,
    flex: 1,
    // borderWidth: 1,
  },
  phoneNumberWarningCtn: {
    // marginTop: 2,
    // borderWidth: 1,
  },
  phoneNumberWarningTxt: {
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize: 12,
    color: warningTxt,
  },
  LoadingWalla: {
    color: backgroundColorNew,
    fontSize: 28,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  mbContainer: {
    width: '82%',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: grayColorOutline,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 1,
  },
  mbArrowContainer: {
    width: '18%',
    backgroundColor: arrowBtnFill,
    justifyContent: 'center',
    marginLeft: 2,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
  },
  mbcountryCode: {
    fontSize: 20,
    fontFamily: 'PlusJakartaSans-SemiBold',
    marginRight: 5,
    color: countryCode,
  },
  mbdivider: {
    height: '100%',
    width: 1,
    backgroundColor: '#ccc',
    marginHorizontal: 8,
  },
  mbphoneInput: {
    flex: 1,
    fontSize: 20,
    fontFamily: 'PlusJakartaSans-SemiBold',
    color: '#636363',
    // borderWidth: 1,
    backgroundColor: 'white',
  },
  mbbutton: {
    alignItems: 'center',
  },
  WelcomeTruckTitle: {
    color: titleColor,
    fontSize: 28,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Bold',
    // paddingHorizontal: 20,
    // borderWidth: 1,
  },
  signupTextContainer: {
    justifyContent: 'space-between',
    alignContent: 'space-between',
  },
  signupWelcomeTitle: {
    fontSize: 16,
    color: textRed,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  signupTopTitle: {
    fontSize: 20,
    marginTop: 10,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  verifyOtpNumber: {
    color: verifyOtpNumber,
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize: 16,
  },
  languageTitle: {
    fontSize: 18,
    marginTop: 20,
    lineHeight: 20,
    maxWidth: 275,
    width: '100%',
    color: PrivacyPolicy,
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  label: {
    fontWeight: '700',
    fontSize: 15,
    color: 'black',
    marginTop: 34,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  textInput: {
    paddingVertical: 0,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderStartWidth: 2,
    borderColor: '#ddd',
  },
  button: {
    flexDirection: 'row',
    borderRadius: 10,
    height: 50,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    width: '100%',
    // maxWidth: 255,
    marginTop: 20,
    // marginBottom: 10,
  },
  backIconView: {
    width: 38,
    height: 38,
    elevation: 2,
    margin: 1,
    backgroundColor: 'white',
    marginBottom: 10,
    borderRadius: 8,

    justifyContent: 'center',
    alignItems: 'center',
  },

  buttonTitile: {
    fontWeight: 'bold',
    color: textColor,
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  policyTitle: {
    color: PrivacyPolicy,
    fontFamily: 'PlusJakartaSans-Medium',
    fontSize: 12,
    textAlign: 'center',
  },
  policyLinkTitle: activate => ({
    textDecorationLine: 'underline',
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize: 12,
    // color: activate ? GradientColor3 : PrivacyPolicy,
    color: activate ? backgroundColorNew : PrivacyPolicy,
    textAlign: 'center',
  }),
  otpResendView: {
    width: '85%',
    marginLeft: 20,
    flexDirection: 'colume',
    alignItems: 'flex-start',
    // borderWidth: 1,
  },
  enterOtp: {
    fontFamily: 'PlusJakartaSans-ExtraBold',
    fontSize: 20,
    color: '#3F3F3F',
  },
  InputView: {
    backgroundColor: back_color,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 14,
    marginTop: 12,
    borderRadius: 8,
  },
  Input: {
    width: '80%',
    fontFamily: 'PlusJakartaSans-Medium',
    fontSize: 15,
    marginLeft: 8,
  },
  Container: {
    backgroundColor: '#FFFDFD',
    // padding: 10,
    flex: 1,
    // borderWidth: 1,
  },
  SignupImage: {
    width: '100%',
    height: '40%',
    maxWidth: 255,
    alignSelf: 'center',
  },
  checkBoxContainer: {flexDirection: 'row', alignItems: 'center'},
  checkBoxStyle: {marginRight: 10},
  centerItem: {
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
  },
  buttonBox: {marginTop: 20, marginHorizontal: 55},
  timer: {
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  otpContainer: {
    // justifyContent: 'center',
    // alignItems: 'center',
    maxWidth: '85%',
    marginLeft: 20,
    marginTop: 40,
    // borderWidth: 1,
  },
  otpView: {
    // maxWidth: '85%',
    // marginTop: 40,
    // borderWidth: 1,
  },
  focusStick: {backgroundColor: 'white'},
  inputsContainer: {width: '100%'},
  pinCodeContainer: {
    width: 70,
    height: 70,
    fontSize: 22,
    borderRadius: 8,
    // backgroundColor: '#FFF',
    borderWidth: 3,
    borderColor: '#ddd',
  },
  pinCodeText: {
    // color: '#595959',
    fontFamily: 'PlusJakartaSans-ExtraBold',
    fontSize: 32,
  },
  setPrivacyStyle: {color: PrivacyPolicy},
  activePinCodeContainer: {
    backgroundColor: GradientColor2,
    color: pageBackground,
  },
  policyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
});
