import {StyleSheet} from 'react-native';
import {
  GradientColor2,
  pageBackground,
  blueButton,
  titleColor,
  inputColor,
  white,
  black,
  PrivacyPolicy,
  seperator,
  shimmerColor,
  divider,
  GradientColor3,
} from '../Color/color';

export default StyleSheet.create({
  linearGradient: {
    height: '100%',
    width: '100%',
  },
  headerView: {flexDirection: 'row', width: '100%'},
  backIconView: {
    width: 38,
    height: 38,
    // elevation: 2,
    margin: 1,
    backgroundColor: 'white',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyBackIconView: {
    backgroundColor: 'transparent',
    width: 38,
    height: 38,
    marginBottom: 24,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  WelcomeTruckTitle: {
    fontWeight: '700',
    color: 'black',
    fontSize: 22,
    textAlign: 'center',
    fontFamily: 'PlusJakartaSans-Medium',
  },
  backgroundView: {
    padding: 20,
    backgroundColor: pageBackground,
    height: '100%',
  },
  title: {
    fontSize: 20,
    width: '80%',
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  bannerContainer: {
    height: '90%',
    borderRadius: 10,
    flexDirection: 'row',
    paddingHorizontal: 5,
  },
  bannerInnerView: {
    flex: 2,
    padding: 20,
  },
  bannerText: {
    fontSize: 14,
    color: white,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  bannerButton: {
    fontSize: 12,
    padding: 10,
    backgroundColor: blueButton,
    color: white,
    width: 100,
    textAlign: 'center',
    borderRadius: 28,
    marginTop: 15,
  },
  normalFlex: {
    flex: 1,
  },
  bannerImage: {
    height: '100%',
    width: '100%',
    borderRadius: 8,
  },
  toolbarContainer: (modal, color) => ({
    flexDirection: modal ? 'row-reverse' : 'row',
    width: '100%',
    padding: color ? 20 : 0,
  }),
  dashboardHeaderContainer: marginBottom => ({
    flexDirection: 'row',
    marginBottom: marginBottom ? 0 : 20,
    justifyContent: 'space-between',
    alignItems: 'center',
  }),
  dashboardHeaderImage: {
    height: 40,
    width: 40,
    // elevation: 2,
    borderRadius: 10,
  },
  dashboardRoundImage: {
    height: 30,
    width: 30,
    borderRadius: 10,
  },
  dashboardHeaderTextView: {
    flex: 1,
    marginLeft: 15,
  },
  lorryShimmerItemView: {
    marginTop: 10,
    flexDirection: 'row',
  },
  dashboardHeaderTextShimmer: {
    width: '100%',
    height: 15,
    borderRadius: 5,
  },
  dashboardHeaderTitle: {
    fontSize: 17,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  rowDirection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowDirectionShimmer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dashboardHeaderVerifiedTitle: color => ({
    fontSize: 12,
    color: color ? 'green' : GradientColor2,
    fontFamily: 'PlusJakartaSans-SemiBold',
    marginLeft: 5,
  }),
  headerCallView: {
    flexDirection: 'row',
    height: '100%',
    justifyContent: 'flex-end',
    alignItems: 'center',
    flex: 1,
  },
  acTime: {fontSize: 10, color: 'green', marginTop: 5},
  editButton: {
    fontSize: 11,
    fontWeight: '500',
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  callButtonView: {
    padding: 10,
    backgroundColor: GradientColor2,
    width: 100,
    justifyContent: 'center',
    borderRadius: 28,
    flexDirection: 'row',
  },
  callText: {
    fontSize: 13,
    color: white,
    textAlign: 'center',
  },
  iconView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  commonMargin: {
    marginRight: 15,
  },
  wallet: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 5,
  },
  inputLabel: {
    backgroundColor: inputColor,
    marginTop: 12,
    marginBottom: 20,
    borderRadius: 8,
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: 'row',
    color: black,
  },
  menuItem: {
    fontSize: 14,
    color: titleColor,
    fontWeight: '500',
    fontFamily: 'PlusJakartaSans-Medium',
  },
  logOut: {
    fontSize: 14,
    color: GradientColor2,
    fontWeight: '500',
    fontFamily: 'PlusJakartaSans-Medium',
  },
  indicatorStyle: {
    marginRight: 10,
  },
  notificationItemView: {
    backgroundColor: white,
    borderRadius: 8,
    flexDirection: 'row',
    elevation: 2,
    margin: 5,
    padding: 10,
  },
  notificationIconView: {height: 40, width: 40, borderRadius: 10},
  notificatioView: {marginLeft: 15},
  searchLocationText: {
    fontSize: 15,
    padding: 5,
    margin: 5,
    color: PrivacyPolicy,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  notificationTitle: {
    fontSize: 14,
    color: titleColor,
    fontWeight: '700',
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  notitficationDesc: {
    fontSize: 12,
    color: PrivacyPolicy,
    fontWeight: '400',
    fontFamily: 'PlusJakartaSans-Regular',
  },
  innerbuttonStyle: {
    padding: 10,
    width: 100,
    borderRadius: 8,
    backgroundColor: pageBackground,
    marginTop: 10,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  innerButtonText: isGrey => ({
    fontSize: 13,
    color: isGrey ? black : white,
    fontFamily: 'PlusJakartaSans-Medium',
    textAlign: 'center',
  }),
  countMsg: {
    position: 'absolute',
    right: -5,
    top: -5,
    zIndex: 1,
    backgroundColor: '#fff',
    paddingVertical: 1,
    paddingHorizontal: 1,
    width: 20,
    height: 20,
    borderRadius: 100,
    color: '#000',
    borderWidth: 2,
    borderColor: GradientColor2,
    fontWeight: 'bold',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  gradientButtonStyle: {
    padding: 8,
    width: 100,
    borderRadius: 8,
    justifyContent: 'center',
    flexDirection: 'row',
    position: 'relative',
  },

  seperatorView: {
    height: 0.5,
    width: '100%',
    backgroundColor: seperator,
    margin: 5,
  },
  menuView: {
    flexDirection: 'row',
    padding: 10,
  },
  menuImage: {height: 50, width: 50, borderRadius: 10},
  menuTtile: {
    fontSize: 14,
    color: titleColor,
    fontWeight: '700',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  menuDesc: {
    fontSize: 12,
    color: PrivacyPolicy,
    fontWeight: '400',
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
  menuDivider: {
    width: '100%',
    height: 1,
    backgroundColor: shimmerColor,
    marginTop: 5,
    marginBottom: 5,
  },
  postItemView: {
    borderRadius: 8,
    elevation: 2,
    margin: 5,
    backgroundColor: white,
    padding: 10,
  },
  postItemDivider: {backgroundColor: shimmerColor, height: 0.5},
  postItemTitle: {
    marginTop: 10,
    fontSize: 12,
    color: PrivacyPolicy,
    fontWeight: '400',
    fontFamily: 'PlusJakartaSans-Regular',
  },
  postItemText: {
    fontSize: 14,
    color: titleColor,
    fontWeight: '500',
    fontFamily: 'PlusJakartaSans-Bold',
  },
  searchFilter: {
    backgroundColor: white,
    flexDirection: 'row',
    elevation: 2,
    marginTop: 18,
    borderRadius: 8,
    marginHorizontal: 5,
  },
  searchLeftText: {
    flex: 1,
    textAlign: 'center',
    justifyContent: 'center',
    fontSize: 13,
    alignSelf: 'center',
    width: 50,
    textTransform: 'uppercase',
    color: PrivacyPolicy,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  searchDivider: {
    width: 1,
    height: 50,
    backgroundColor: divider,
  },
  searchInput: {
    flex: 4,
    marginLeft: 10,
    alignSelf: 'center',
  },
  locationIcon: {
    flex: 1,
    textAlign: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    // borderWidth: 1,
  },
  searchText: {fontFamily: 'PlusJakartaSans-Bold', color: PrivacyPolicy},
  //
  detailItem: {
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detailText: {
    fontSize: 16,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
    fontWeight: '700',
    marginLeft: 10,
  },
  flexDirection: {flexDirection: 'row'},

  //
  card: {
    borderRadius: 8,
    elevation: 2,
    backgroundColor: white,
    padding: 10,
    margin: 10,
    marginBottom: 10,
  },
  horizontalLine: {backgroundColor: '#AFAFAF', height: 1, marginVertical: 10},
  verticalLine: {
    backgroundColor: '#AFAFAF',
    width: 2,
    marginHorizontal: 15,
    height: '100%',
  },
  textStyle: {
    color: PrivacyPolicy,
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  rowdirection: {flexDirection: 'row', alignItems: 'center'},
  smallImageHeaderTitle: {
    fontSize: 15,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  point: {
    height: 8,
    width: 8,
    backgroundColor: PrivacyPolicy,
    borderRadius: 4,
    marginRight: 20,
    marginLeft: 10,
  },
  requestButtonContainer: {
    borderWidth: 2,
    borderRadius: 8,
    borderColor: GradientColor3,
  },
  findButtonContainer: {
    marginLeft: 20,
    borderWidth: 2,
    borderRadius: 8,
    backgroundColor: GradientColor3,
    borderColor: GradientColor3,
  },
  gradientButtonText: {
    fontSize: 13,
    color: GradientColor3,
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
  },
  findButtonText: {
    fontSize: 13,
    color: white,
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
  },
  btnContainer: {flexDirection: 'row', justifyContent: 'flex-end'},
});
