import {StyleSheet} from 'react-native';
import {pageBackground, textColor, titleColor} from '../../Color/color';
import {PrivacyPolicy} from '../../Color/color';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  mapContainer: {
    flex: 1
  },
  gpsTrackContainer: {
    padding: 10,
    flex: 1,
  },
  gpsTrackHeaderContainer: {
    marginVertical: 10,
  },
  gpsTrackBtnStyle: {
    flexDirection: 'row',
    borderRadius: 8,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 5,
  },
  loadingStyle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noAddressContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noAddressText: {
    fontSize: 16,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  fullScreenContainer: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  screenModalView: {
    flex: 1,
    justifyContent: 'center',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    backgroundColor: pageBackground,
    maxHeight: 400,
    padding: 20,
  },
  header: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
  },
  speedBox: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  gpsRelayHeaderText: {
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
    color: titleColor,
    marginRight: 5,
  },
  headerValue: {
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
    color: '#EF4D23',
  },
  relayTextContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  relayText: {
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 20,
    color: titleColor,
  },
  relayTextBold: color => ({
    fontFamily: 'PlusJakartaSans-ExtraBold',
    fontSize: 20,
    color: color ? 'red' : '#3BA700',
    marginLeft: 5,
  }),
  descriptionBox: {
    marginTop: 10,
    paddingHorizontal: 10,
    marginHorizontal: 40,
  },
  descriptionText: {
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize: 12,
    color: titleColor,
    textAlign: 'center',
  },
  descriptionTextBold: color => ({
    fontFamily: 'PlusJakartaSans-ExtraBold',
    fontSize: 12,
    color: color ? 'red' : '#3BA700',
  }),
  gpsRelayBtnStyle: color => ({
    borderWidth: 2,
    borderRadius: 50,
    backgroundColor: color ? 'red' : '#3CA604',
    borderColor: color ? 'red' : '#3CA604',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    width: '60%',
    alignSelf: 'center',
    marginTop: 20,
  }),
  gpsRelayBtnText: {
    fontSize: 14,
    color: textColor,
    fontFamily: 'PlusJakartaSans-ExtraBold',
    textAlign: 'center',
    width: 150,
  },
  gpsRelayIconBox: {
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#F7F7F7',
    marginBottom: 10,
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noDataContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noDataText: {
    fontSize: 16,
    color: PrivacyPolicy,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  notificationContainer: {
    flex: 4,
    backgroundColor: '#ffffff',
    padding: 20,
    elevation: 2,
  },
  notificationHeader: {
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 14,
  },
  headerBox: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: '#FFFFFF',
    // elevation: 2,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#00000029',
  },
  mediumTextStyle: {
    color: PrivacyPolicy,
    fontFamily: 'PlusJakartaSans-Medium',
    fontSize: 12,
  },
  gpsAlertHeaderText: {
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-SemiBold',
    textTransform: 'capitalize',
  },
  timeText: {
    fontSize: 8,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  textView: {
    flexDirection: 'column',
    justifyContent: 'center',
    // borderEndWidth: 1,
  },
  speedBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flex: 1,
  },
  callBox: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconBox: {
    borderRadius: 20,
    padding: 5,
    backgroundColor: '#f7f7f7',
    elevation: 2,
    marginVertical: 5,
  },
  settingsContainer: {
    flex: 1,
    padding: 10,
    paddingBottom: 50,
    backgroundColor: '#ffffff',
    marginBottom: 10,
    elevation: 2,
  },
  settingsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  fuelPumpContainer: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 10,
    marginVertical: 5,
    paddingHorizontal: 15,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 8,
    elevation: 2,
  },
  iconContainer: {
    padding: 3,
    elevation: 2,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    transform: [{rotate: '45deg'}],
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    fontSize: 16,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  headerTextValue: {
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-SemiBold',
    color: PrivacyPolicy,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailBox: {
    maxWidth: '73%'
  },
  listContainer: {
    flex: 1,
    borderWidth: 0,
    marginHorizontal: 10,
    backgroundColor: '#ffffff',
    paddingVertical: 15,
    paddingHorizontal: 10,
    elevation: 2,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  label: {
    fontSize: 15,
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  deliveryDetailsBtnStyle: {
    flexDirection: 'row',
    borderRadius: 6,
    paddingHorizontal: 25,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 30,
  },
  deliveryDetailsBtnText: {
    color: textColor,
    fontSize: 14,
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
  },
  rateContainer: {
    margin: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    elevation: 2,
    paddingVertical: 15,
    padding: 5,
  },
  rateHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  rateHeaderView: {
    borderWidth: 0, 
    padding: 8
  },
  planTitle: {
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 14,
    color: titleColor,
    textTransform: 'capitalize',
  },
  discountContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 5,
  },
  discountText: {
    fontFamily: 'PlusJakartaSans-Light',
    fontSize: 12,
    color: '#0F8B00',
    marginLeft: 5,
  },
  priceContainer: {
    paddingVertical: 10,
    backgroundColor: '#EFFFE6',
    borderRadius: 6,
    paddingHorizontal: 15,
  },
  oldPrice: {
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize: 12,
    textDecorationLine: 'line-through',
  },
  newPrice: {
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 14,
    color: '#0F8B00',
  },
  planContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginVertical: 8,
  },
  planText: {
    fontFamily: 'PlusJakartaSans-Medium',
    fontSize: 14,
    textTransform: 'capitalize',
  },
  loader: {
    flex: 1, 
    alignItems: 'center', 
    justifyContent: 'center'
  },
  loaderContainer: {
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center'
  },
  gpsButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 35,
    height: 35,
    borderRadius: 25,
    backgroundColor: '#FFFFFF',
    elevation: 3,
    position: 'absolute',
    bottom: 150,
    right: 10,
  },
  bottomContainer: {
    backgroundColor: '#FFF7F5',
    position: 'absolute',
    bottom: 0,
    padding: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    width: '100%',
    elevation: 3,
    borderColor: '#F7F7F7',
    borderWidth: 1,
  },
  geozoneContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingVertical: 10,
    borderColor: '#00000029',
    borderWidth: 1,
  },
  geozoneText: {
    marginHorizontal: 15,
    fontSize: 10,
    fontFamily: 'PlusJakartaSans-Regular',
  },
  sliderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
  },
  noGpsAvailTxt: {
    color: '#707070',
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 28,
  },
  slider: {width: '75%'},
  textvalue: {
    width: '20%',
    textAlign: 'center',
    borderRadius: 3,
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 12,
    borderWidth: 0.3,
    paddingVertical: 5,
    marginRight: 5,
    backgroundColor: '#FFFFFF',
  },
  inputContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 15,
  },
  inputLabel: {
    marginRight: 15,
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Regular',
  },
  textInput: {
    borderBottomWidth: 1,
    flex: 1,
    paddingVertical: 0,
    fontSize: 12,
    fontFamily: 'PlusJakartaSans-Bold',
  },
  geozoneAbsFillObj: {
    ...StyleSheet.absoluteFillObject,
  }, 
  addGeozoneBtnStyle: {
    borderRadius: 8,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    marginTop: 20,
    width: '100%',
  },
  getGpsPlanTxt: {
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 14,
    marginTop: 15,
  },
  dashboardHeaderView: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    elevation: 5,
    maxHeight: 60,
    padding: 10,
    backgroundColor: '#FFFFFF',
    zIndex: 9999,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  contentContainer: {
    flex: 1,
    marginVertical: 60,
    padding: 10,
  },
  loadingStyle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notFoundText: {
    color: '#707070',
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 28,
  },
  notFoundView: {
    // borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnStyle: {
    borderWidth: 2,
    borderRadius: 8,
    backgroundColor: '#3CA604',
    borderColor: '#3CA604',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    width: '50%',
    alignSelf: 'center',
  },
  btnText: {
    fontSize: 16,
    color: textColor,
    fontFamily: 'PlusJakartaSans-Bold',
    textAlign: 'center',
  },
  homeView: {
    flex: 1,
    marginVertical: 60,
    justifyContent: 'center',
  },
  notFoundView: {
    flex: 0.75,
    justifyContent: 'center',
    alignItems: 'center',
  },
  getNowView: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 0.25,
  },
  offerText: {
    fontFamily: 'PlusJakartaSans-Medium',
    fontSize: 14,
    color: '#3BA700',
    textAlign: 'center',
    paddingVertical: 10,
  },
  splashImage: (height, width) => ({
    height: height,
    width: width,
  }),
  subText: {
    color: titleColor,
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 14,
    marginTop: 15,
  },
});
